# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: '#about'
    weight: 10
  - name : 'Formations'
    identifier: formation
    # url: '#training'
    weight: 20
  - name: 'ğŸ™ï¸ Prise de son et mixage'
    url: trainings/pds-mix
    parent: formation
    weight: 10
  - name: 'ğŸ”ˆ initiation 3D Sonore'
    # url: 
    parent: formation
    weight: 20
  - name: 'ğŸ§ Binaural'
    url: trainings/spat-revo
    parent: formation
    weight: 30
  - name: 'ğŸ›ï¸ SPAT Revolution'
    url: trainings/spat-revo
    parent: formation
    weight: 30
  - name: 'ğŸšï¸ REAPER'
    url: trainings/reaper
    parent: formation
    weight: 40
  - name: Projets
    # url: '#projects'
    identifier: projets
    weight: 30
  - name: 'ğŸ¤˜ Outwards'
    url: project/outwards
    parent: projets
    weight: 10
  - name: 'ğŸ” Burger Bang'
    url: project/burgerbang
    parent: projets
    weight: 20
  - name: Guide pratique des techniques du son
    url: https://jpecquais.github.io/doc-technique-son/
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
